
AWSTemplateFormatVersion: '2010-09-09'
Description: 'VSTS managed role for federated access to DynamoDB'
Resources:
  AppAdmin:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:saml-provider/Ping'
          Action: sts:AssumeRoleWithSAML
          Condition:
            StringEquals:
              SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Path: /
      RoleName: DynamoReader

---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'SecOpsDynamoUser'
Resources:
  SecOpsDynamoUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: SecOpsDynamoUser
  SecOpsDynamoDBPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: DynamoDBRead
          Effect: Allow
          Action:
          - "application-autoscaling:DescribeScalableTargets"
          - "application-autoscaling:DescribeScalingActivities"
          - "application-autoscaling:DescribeScalingPolicies"
          - "cloudwatch:DescribeAlarmHistory"
          - "cloudwatch:DescribeAlarms"
          - "cloudwatch:DescribeAlarmsForMetric"
          - "cloudwatch:GetMetricStatistics"
          - "cloudwatch:ListMetrics"
          - "datapipeline:DescribeObjects"
          - "datapipeline:DescribePipelines"
          - "datapipeline:GetPipelineDefinition"
          - "datapipeline:ListPipelines"
          - "datapipeline:QueryObjects"
          - "dynamodb:BatchGetItem"
          - "dynamodb:DescribeTable"
          - "dynamodb:GetItem"
          - "dynamodb:ListTables"
          - "dynamodb:Query"
          - "dynamodb:Scan"
          - "dynamodb:DescribeReservedCapacity"
          - "dynamodb:DescribeReservedCapacityOfferings"
          - "dynamodb:ListTagsOfResource"
          - "dynamodb:DescribeTimeToLive"
          - "dynamodb:DescribeLimits"
          - "dynamodb:ListGlobalTables"
          - "dynamodb:DescribeGlobalTable"
          - "dynamodb:DescribeBackup"
          - "dynamodb:ListBackups"
          - "dynamodb:DescribeContinuousBackups"
          - "dax:Describe*"
          - "dax:List*"
          - "dax:GetItem"
          - "dax:BatchGetItem"
          - "dax:Query"
          - "dax:Scan"
          - "ec2:DescribeVpcs"
          - "ec2:DescribeSubnets"
          - "ec2:DescribeSecurityGroups"
          - "iam:GetRole"
          - "iam:ListRoles"
          - "sns:ListSubscriptionsByTopic"
          - "sns:ListTopics"
          - "lambda:ListFunctions"
          - "lambda:ListEventSourceMappings"
          - "lambda:GetFunctionConfiguration"
          Resource: '*'
          Condition:
            IpAddress:
              aws:SourceIp:
              - '192.189.128.0/23'
              - '12.2.142.0/24'
      Users: 
        - !Ref SecOpsDynamoUser
 
 

 
 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ReadOnlyAPIActionsOnBooks",
            "Effect": "Allow",
            "Action": [
                "dynamodb:GetItem",
                "dynamodb:BatchGetItem"
            ],
            "Resource": "arn:aws:dynamodb:us-west-2:123456789012:table/Books"
        }
    ]
}